
<CENTER>
<div style=width:600px;border-radius:10px;height:200px;background-color:#ffcccc;text-align:center;vertical-align:middle;>

<font size=14, font color=navy>  
<font size=14, font color=navy>Programmation Python

</div>
</CENTER>

# TYPES SIMPLES

* Expressions $\rightarrow$ evaluation $\rightarrow$ valeurs
* Instructions $\rightarrow$ Execution $\rightarrow$ action

In [1]:
3+1-2

2

In [2]:
a=3

In [4]:
L=[]
L.append(3)
L

[3]

* Valeur $\leftrightarrow$ Type
* Type $\rightarrow$ (Groupe + Caractéristiques communes) :
    * Représentation mémoire
    * Syntaxe

# Entier <i>int</i>

* Taille illimitée ( $\verb"long"$>64 bits en 2.x)
* Base au choix ($\verb"0=0o"$, $\verb"0=0x"$, $\verb"0=0b"$) 

In [5]:
type(11)

int

In [6]:
0o11,0x11,0b11

(9, 17, 3)

In [7]:
0x11a

282

In [1]:
a=2.e65
b=int(a)
type(b)
# change kernel

long

### Opérateurs

* +, - , \* , \*\* : exponentiation
* / ou // (sans ambiguité) : quotient DE
* % : reste DE

exponentiation>multiplication/division>
          modulo>addition/soustraction
          
évaluation gauche $\rightarrow$ droite

In [2]:
1+2**6

65

In [3]:
(1+2)**6

729

In [4]:
6%2**2

2

In [5]:
(6%2)**2

0

# Flottants <i>float</i>

### IEEE 754

* <b>Simple précision</b> : 32 bits :
    * 1 (signe) + 8 (-126$\leqslant$exposant$\leqslant$127) + 23 (mantisse)
    
* <b>Double précision</b> : 64 bits :
    * 1 (signe) + 11 (-1022$\leqslant$exposant$\leqslant$1023) + 52 (mantisse)   

$\rightarrow$ de $2^{-1074}$ à $2^{1024}-2^{971}$   
$\rightarrow$ non-continument : nombre <b>fini</b>  
$\rightsquigarrow$ <b>Erreurs d'arrondis !</b>

In [6]:
import numpy as np
np.sin(np.pi)

1.2246467991473532e-16

In [7]:
0.1+0.2

0.30000000000000004

#### Notation scientifique

In [8]:
6.001e3

6001.0

##### Arrondir

In [19]:
import numpy as np
np.pi

3.141592653589793

In [21]:
round(np.pi,4)    

3.1416

In [23]:
print("%.2f") %np.pi

3.14


In [24]:
float("{:.2f}".format(np.pi)),float("{:.2}".format(np.pi))

(3.14, 3.1)

2.0

#### Opérateurs

* +, - , \* , \*\* : exponentiation
* / (sans ambiguité)

exponentiation>multiplication/division>

   addition/soustraction
          
évaluation gauche $\rightarrow$ droite

#### Division des réels entiers

In [25]:
type(11.)

float

In [26]:
(11.).is_integer(),(11.00000001).is_integer()

(True, False)

In [1]:
a=3
a/2,type(a)
#change Kernel

(1, int)

In [2]:
from __future__ import division
3/2,3//2

(1.5, 1)

In [3]:
float(a)/2,a/2.

(1.5, 1.5)

In [7]:
a=3.
type(a)#non mutabilite 

float

#### Transtypage inverse

In [9]:
int(11.0),int(3.6)

(11, 3)

In [10]:
int(-.5)

0

$\verb"int(a)"=\text{sign}(x)\lfloor x\rfloor \neq \lfloor x\rfloor$

#### Fonctions : module maths

In [11]:
import math
dir(math)

['__doc__',
 '__file__',
 '__name__',
 '__package__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'hypot',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'modf',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'trunc']

In [12]:
#Exemple
math.cosh(0)
math.sin(math.pi/3)

0.8660254037844386

#### A propos des importations

In [13]:
import math
sin(0)

NameError: name 'sin' is not defined

$\rightarrow$ Importation <i>globale</i> <b>avec</b> préfixe

In [14]:
math.sin(0)

0.0

In [15]:
from math import sin
sin(0)

0.0

$\rightarrow$ Importation <i>individuelle</i> <b>sans</b> préfixe

In [16]:
from math import *
cos(0)

1.0

$\rightarrow$ Importation <i>globale</i> <b>sans</b> préfixe    
$\rightsquigarrow$ Technique de "<i>brute</i>" : à proscrire !

In [19]:
from math import sin
def sin():
    return "peche capital"

sin(0),sin()

'peche capital'

#### Aliasing

In [21]:
import numpy as np#Nom court : c'est bien !
np.cos(0)

1.0

In [22]:
import math
def sin():
    return "peche capital"
np.sin(np.pi),sin(),math.sin(math.pi)

(1.2246467991473532e-16, 'peche capital', 1.2246467991473532e-16)

# Autres types de nombres

### Complexes

In [23]:
a=1+2j
b=complex(1,-2)
type(a),type(b)

(complex, complex)

In [26]:
a.real,a.imag

(1.0, 2.0)

In [27]:
c=a.conjugate()
#a,b,c,b==c,a*b
a*b==a*c

True

In [28]:
float(a),int(a)

TypeError: can't convert complex to float

### Fractions

In [29]:
import fractions as fr
a=fr.Fraction(1,2)
b=fr.Fraction(2,7)
type(a),a*b

(fractions.Fraction, Fraction(1, 7))

### Decimaux

In [30]:
import decimal as deci
a=deci.Decimal('1.23')
b=deci.Decimal(1.23)
type(a),a,b

(decimal.Decimal,
 Decimal('1.23'),
 Decimal('1.229999999999999982236431605997495353221893310546875'))

C'est l'entier codable en mémoire le plus proche de 1.23...    
$\rightarrow$ $\verb"Decimal"$ pour du calcul exact

# Booléens <i>bool</i>

* $\verb"True"$ et $\verb"False"$
* Instructions ($\verb"if...elif...else..."$) et Boucles ($\verb"while..."$) <i>conditionnelles</i>    
    $\rightarrow$ brique indispensable !

* $\verb"False"$ :    
    * $\verb"False"$ (évidemment)
    * $\verb"None"$
    * $\verb"[]"$ ou $\verb"(,)"$ 
    (liste ou tuple ou chaine de caractères vide)
    * Le nombre 0 (indépendamment du type)
    
* $\verb"True"$ : tout le reste...

Seulement dans les <b>conditionnelles</b>

In [36]:
def test_bool(a):
    if a :
        return True
    else:
        return False

[]

In [38]:
test_bool(False),test_bool(None),test_bool([]),\
test_bool(()),test_bool(0),\
test_bool(0.0),test_bool(np.sin(np.pi)),test_bool(''),\
test_bool(1),test_bool([1]),test_bool('lapin')

(False, False, False, False, False, False, True, False, True, True, True)

<b>Attention</b> : Ca ne marche pas (toujours) avec les tests d'égalité structurelle

In [42]:
#Attention
1==True,1.==True,()==True,[]==True,[1]==True,'lapin'==True

(True, True, False, False, False, False)

#### Opérateurs

* $\verb".not."$, $\verb".or."$ ou $\verb".|."$, $\verb".and."$ ou $\verb".&."$ et $\verb".^."$(ou exclusif)
* Tables de vérité


#### Comparaisons

* Obtention de booléens $\leftrightarrow$ Test
* <, <=, >, >=, ==, !=, $\verb"is"$, $\verb"is not"$ ((in)égalité physique)
* Comparaisons successives autorisées

In [43]:
a=0
a<5,-1<a<5,(1<a) and (a<5)

(True, True, False)

#### Nécessité d'un type commun ?

In [44]:
2>3, 2.<3,3.<2

(False, True, False)

In [45]:
[1,2,3]<[1,2,4]

True

In [46]:
[1,2,3,4]<[1,2,4]

True

In [49]:
[1,11,2]<[1,2,16]

False

In [50]:
'lapin'<'chien'

False

In [57]:
'chien'<'lapine'

True

In [54]:
['a','coati']<['a','r'], ['a',24]>['a',12]

(True, True)

In [58]:
[1,3]<(1,11,6)

True

In [59]:
(1,3)<[1,11,6]

False

In [62]:
[1]<[1,()]

True

# TYPES COMPOSES

* Type composé : données faisant intervenir d'autres type
* Structure de données $\leftrightarrow$ Implémentation Type composé

# Listes <i>list</i>

* Conteneur universel, séparateurs $\verb"[,]"$
* Construction :
    * Extension
    * Compréhension : $\verb"[f(i) for i in iterable if P(i)]"$
    * Copie

In [48]:
L=[1,2,'lapin',(1,9)]

4

In [65]:
L=[2*i for i in range(10)]
L

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [66]:
nonpremier49=[j for i in range(2,8) for j in range(i*2,50,i)]
premier49=[x for x in range(50) if x not in nonpremier49]
premier49

[0, 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]

#### Caractéristiques

* Itérable
* Mutable (modifications en place, références multiples)

#### Copie

In [67]:
L=[1,2,3]
M=L
M.append(4)
L

[1, 2, 3, 4]

<b>Mutabilité !</b>

#### Solution

In [68]:
L=[1,2,3]
M=[x for x in(L)]#iterable

In [69]:
import copy
N=copy.deepcopy(L)

In [70]:
M.pop()
N.append(7)
L,M,N

([1, 2, 3], [1, 2], [1, 2, 3, 7])

In [57]:
O=L+[]
P=L[:]#slicing
O,P

([1, 2, 3], [1, 2, 3])

#### Accès et modification d'éléments

* $\verb"L[i]"$
* $\verb"L[i]=x"$ (en place)

In [71]:
L=[1,7,8,9,0,4,12]
L[1]

7

Indexation par $[\! |0,n[\! |$

(intervalle semi ouvert à droite)    
    $\rightarrow$ comme $\verb"range"$

In [74]:
L

[1, 2, 8, 9, 0, 4, 12]

In [75]:
M=L
M[0]=0
L

[0, 2, 8, 9, 0, 4, 12]

In [73]:
L[1]=2
L

[1, 2, 8, 9, 0, 4, 12]

Modification en place

#### Opérateurs

* \+ : concaténation
* \* : concaténations répétées

In [77]:
L,M=[1,2,3],[4,5]
L*3
L+M

[1, 2, 3, 4, 5]

Concaténation $\rightarrow$ Création nouvelle liste et référence

In [80]:
M=[0]*3 ; L=[M for i in range(3)] ; L[0][0]=1 ; L
L=[[0]*3]*3 ; L[0][0]=1 ; L
L=[[0 for i in range(3)] for j in range(3)] ; L[0][0]=1 ; L

[[1, 0, 0], [0, 0, 0], [0, 0, 0]]

Attention aux répétitions d'objets mutables.

#### Méthodes

append(x), extend(M), insert(i,x), remove(x), pop(i)
index(x), count(x), sort(), reverse()

In [98]:
#Essai... en place ou non ?
L=['lapin',7.,[]]
L.sort()
L

#L=L+[1,5,7]

[7.0, [], 'lapin']

Application : copie

In [46]:
L=[1,7,8,9,0,4,12]
M=L+[]
M[0]=0
L,M

([1, 7, 8, 9, 0, 4, 12], [0, 7, 8, 9, 0, 4, 12])

#### Fonctions

len(L), map(f,L) + test d'appartenance

In [101]:
#Essai
import numpy as np
L=[1,7,8,9,0,4,12]
f=np.sqrt
M=map(f,L)
M,L
54 in L

True

#### Slicing

* Slicing, slicing partiel, slicing à pas, indexation négative
* Réassignation de portions $\rightarrow$ suppression de portions

In [ ]:
#Essai

In [102]:
L=[1,7,8,9,0,4,12]
L[1:3]#semi-ouvert à droite

[7, 8]

In [50]:
L[:3],L[3:],L[:]#nouvelles listes

([1, 7, 8], [9, 0, 4, 12], [1, 7, 8, 9, 0, 4, 12])

In [51]:
L=[1,7,8,9,0,4,12]
L[:6:2] 

[1, 8, 0]

In [53]:
L[6::-1]#renversement

[12, 4, 0, 9, 8, 7, 1]

#### Double indexation d'une liste

* de -len(L) à len(L)-1 (n=len(L))
* L[-n]=L[0],L[n-1]=L[1],...,L[-1]=L[n-1],L[0],...L[n-1]

In [105]:
#Accès au dernier
L=[1,7,8,9,0,4,12]
L[-1],L[2:-1],L[-7]#,L[-8]

(12, [8, 9, 0, 4], 1)

#### Assignation de portions

* A la place de la tranche
* De n'importe quelle taille

In [106]:
L=[1,7,8,9,0,4,12]
L[0:2]=[3,4]
L

[3, 4, 8, 9, 0, 4, 12]

In [107]:
L[0:2]=[5,5,5,6]
L

[5, 5, 5, 6, 8, 9, 0, 4, 12]

In [90]:
# Elimination de portions
L[0:3]=[]
L

[6, 8, 9, 0, 4, 12]

# Chaînes de caractères <i>string</i>

* 2.x : Table ASCII étendue (256 car) - 1 octet
* 3.x : Unicode (tous car.) - chaîne unicode

#### Caractères accentués

* Déconseillé
* Sauf pour l'affichage
* Pas d'accent pour variable ou fonction

In [4]:
def dégénéré(a):
    print(a)
dégénéré(4)
dégénéré('dégénéré')

#change Kernel
#change print

4
dégénéré


#### Construction

* Suite de caractères
* Délimités par :
    * Simples quotes '
    * Doubles quotes "
    * Triples simples quotes '''
    * Triples doubles quotes """

In [12]:
s1="une \"chaine\" \\ de \'caracteres\'"
print(s1) 
#varier les quotes 
#introduire guillements et accents et saut ligne
#enlever les accents

une "chaine" \ de 'caracteres'


#### Caractéristiques

* Itérables
* Immutables
* Avant le corps d'une fonction $\rightarrow$ Aide     
    $\rightarrow$ triples quotes/plusieurs lignes    
    $\rightarrow$ Spécification

#### Caractères spéciaux

* Caractères ayant un sens en Python :
    * &, ', ",\,...
    * \n (ou \r) (saut ligne) ; \t (tabulation) ; \b (esp. neg)

In [3]:
s4='une \'chaine\' de caracteres'
print(s4)

une 'chaine' de caracteres


#### Accès aux éléments

* s[i]
* pas d'affectation !

In [13]:
s='une chaine'
for car in s:
    print(car)

u
n
e
 
c
h
a
i
n
e


In [16]:
car=s[1]
car
s[1]='f'

TypeError: 'str' object does not support item assignment

#### Slicing

In [17]:
s1='une chaine de caracteres'
s1[4:9],s1[4:],s1[0],s1[-24],s1[::-1]

('chain', 'chaine de caracteres', 'u', 'u', 'seretcarac ed eniahc enu')

#### Opérateurs

* \+ : concaténation
* \* : concaténations répétées

In [19]:
'bla'+'bli','bla'*4

('blabli', 'blablablabla')

Concaténation et modification

In [20]:
s1='une chaine de caracteres'
s1[:10]+' avec plein'+s1[10:]

'une chaine avec plein de caracteres'

Concaténation par les espaces

In [21]:
s2='une chaine' 'de caracteres'
s2

'une chainede caracteres'

#### Méthodes

s.upper(),s.lower(),s.find(souschaine),    
s.replace(souschaine,rempl),s.strip(),   
s.startswith(souschaine),s.endswith(souschaine)

In [36]:
#Essai
s1.startswith('une')

True

#### Autres

* len(s)
* s.split(separateur)
* D.join(listechaine)

Appartenance avec $\verb"souschaine in s"$

In [41]:
s1='les chaussettes de l\'archiduchesse'
L=s1.split(' ')
L
#'_'.join(L)

"les_chaussettes_de_l'archiduchesse"

#### Insertion

* Dans une chaine
* Nombre (entier, flottant) ou autres chaine
* Indication du point : %i, %f, %s
* Après : %(a,b,...) : tuble de remplacement

In [45]:
s='Il existe %s merveilles du monde' %'7' #7. et 'sept'
print(s)

Il existe 7 merveilles du monde


Pratique pour les boucles

In [46]:
['%i kilometres a pieds, ca use !' %k for k in range(1,10)]

['1 kilometres a pieds, ca use !',
 '2 kilometres a pieds, ca use !',
 '3 kilometres a pieds, ca use !',
 '4 kilometres a pieds, ca use !',
 '5 kilometres a pieds, ca use !',
 '6 kilometres a pieds, ca use !',
 '7 kilometres a pieds, ca use !',
 '8 kilometres a pieds, ca use !',
 '9 kilometres a pieds, ca use !']

In [47]:
def cube(n):
    return n**3
def phrase(n):
    return 'le cube de %i est %i' %(n,cube(n))
phrase(5)

'le cube de 5 est 125'

# Tableaux numpy <i>np.array</i>

* Listes homogènes
* De nombres
* De taille fixe (quoique modifiable)

* Comportement "vectoriel"    
    $\rightarrow$ sens different de * et +
* Création $\verb"np.array(L)"$ :    
    * L liste numérique
    * L liste de listes numériques

In [60]:
import numpy as np
A=np.array([1,2,3,4,9])
B=np.array([1,0,1,0,-1,9])
C=B.reshape((2,3))
C


array([[ 1,  0,  1],
       [ 0, -1,  9]])

In [61]:
#Test
D=3*A ; E=3*B 
A,D,B,E

(array([1, 2, 3, 4, 9]),
 array([ 3,  6,  9, 12, 27]),
 array([ 1,  0,  1,  0, -1,  9]),
 array([ 3,  0,  3,  0, -3, 27]))

In [62]:
A*B

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [63]:
F=np.array([1,-1,0,1,-1])
A,F,A*F

(array([1, 2, 3, 4, 9]),
 array([ 1, -1,  0,  1, -1]),
 array([ 1, -2,  0,  4, -9]))

$\rightarrow$ terme à terme

$ \begin{pmatrix}1&1&1\\ 0& 1 & -1\\ 1&1&0 \end{pmatrix}\cdot \begin{pmatrix} 1&2&1\\ -1&0&1\\ 1&1&1 \end{pmatrix}=\begin{pmatrix}  1&3&3\\ -2&-1&0\\ 0& 2 & 2\end{pmatrix}$

In [64]:
A=np.array([[1,1,1],[0,1,-1],[1,1,0]])
B=np.array([[1,2,1],[-1,0,1],[1,1,1]])
A*B

array([[ 1,  2,  1],
       [ 0,  0, -1],
       [ 1,  1,  0]])

$\rightarrow$ Conclusion ?   
$\rightarrow$  Attention ! Prudence...   
$\rightarrow$ Solution : $\verb"matrix"$

<b>Tableau comme tableau d'indices</b>   
$\rightarrow$ Subtil et pythonnesque

In [65]:
ind=np.array([1,5,9])
tab=np.array([1,2,4,8,16,3,9,27,81,'lapin'])
tab[ind]

array(['2', '3', 'lapin'], 
      dtype='<U21')

In [66]:
ind,tab

(array([1, 5, 9]),
 array(['1', '2', '4', '8', '16', '3', '9', '27', '81', 'lapin'], 
       dtype='<U21'))

<b>Fonctionne avec des booléens</b>   
* Terme à terme   
* Avec toute expression booléenne

In [68]:
A=np.array([1,2,3,4,9,2,0,7,9])
B=A>3
B
C=A%2==1
B,C

(array([False, False, False,  True,  True, False, False,  True,  True], dtype=bool),
 array([ True, False,  True, False,  True, False, False,  True,  True], dtype=bool))

<b>Indexation par les booléens</b>

In [69]:
#Selection
A,A[A>3],A[A%2==1]

(array([1, 2, 3, 4, 9, 2, 0, 7, 9]),
 array([4, 9, 7, 9]),
 array([1, 3, 9, 7, 9]))

<b>Slicing des arrays</b>

In [71]:
A=np.array([[1,2,1],[-1,0,1],[1,1,1]])
#A[0,1]
A,A[0,:]#Premiere ligne
A[0:2,0:2]

array([[ 1,  2],
       [-1,  0]])

<b>Matrices particulières</b>

In [78]:
B=np.zeros((3,4))
C=np.ones((4,3))
I=np.eye(5)
D=np.diag((1,2,3,4))#Fonctionne avec une liste
C

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Matrices numpy <i>np.matrix</i>

* Lever le problème du calcul "terme à terme" (utile !)
* Permettre le calcul matriciel

In [79]:
A=np.array([[1,1,1],[0,1,-1],[1,1,0]])
B=np.array([[1,2,1],[-1,0,1],[1,1,1]]) ; C=A*B
a=np.matrix([[1,1,1],[0,1,-1],[1,1,0]])
b=np.matrix([[1,2,1],[-1,0,1],[1,1,1]]) ; c=a*b
C,c

(array([[ 1,  2,  1],
        [ 0,  0, -1],
        [ 1,  1,  0]]), matrix([[ 1,  3,  3],
         [-2, -1,  0],
         [ 0,  2,  2]]))

In [81]:
a+b

matrix([[ 2,  3,  2],
        [-1,  1,  0],
        [ 2,  2,  1]])

Evidemment... ça marche encore

In [82]:
a,2*a

(matrix([[ 1,  1,  1],
         [ 0,  1, -1],
         [ 1,  1,  0]]), matrix([[ 2,  2,  2],
         [ 0,  2, -2],
         [ 2,  2,  0]]))

Autre solution ($\verb"arrays"$) : $\verb"dot"$

In [69]:
A=np.array([[1,1],[0,1]])
B=np.array([[1,2,1],[-1,0,1]]) ; C=np.dot(A,B)
C

array([[ 0,  2,  2],
       [-1,  0,  1]])

In [89]:
#transpose(a)
a.transpose()
#np.det(a)
#np.trace(a),a.transpose(),a.T

matrix([[ 1,  0,  1],
        [ 1,  1,  1],
        [ 1, -1,  0]])


Il manque les outils usuels d'algèbre linéaire


In [91]:
import numpy.linalg as lg

In [94]:
lg.det(a),np.trace(a)
#lg.trace(a)

(-1.0, 2)

In [95]:
A=np.array([[1,1,1],[0,1,1],[1,1,1]])#ou matrix
lg.matrix_power(A,5)
lg.matrix_rank(A)
lg.inv(a)
b=np.matrix([[1],[2],[5]]) ; lg.solve(a,b)
AA,B=np.array(a),np.array(b) ; lg.solve(AA,B)

array([[ 7.],
       [-2.],
       [-4.]])

<b>Systèmes linéaires</b>

In [81]:
b=np.matrix([[1],[2],[5]]) ; c=lg.solve(a,b)
c

matrix([[ 3.5],
        [-4. ],
        [ 5.5]])

In [82]:
a*c

matrix([[ 1.],
        [ 2.],
        [ 5.]])

In [80]:
AA,B=np.array(a),np.array(b) ; lg.solve(AA,B)

array([[ 3.5],
       [-4. ],
       [ 5.5]])

In [83]:
BB=np.array([1,2,5]) ; lg.solve(AA,BB)

array([ 3.5, -4. ,  5.5])

$\rightarrow$ Dangereux (tailles)

$\rightarrow$  Voir numpy et linalg (cf. Centrale)   
* $\verb"lg.eigvals"$   
 
* $\verb"lg.eig"$   
 
* $\verb"np.vdot"$   
 
* $\verb"np.cross"$   

# Fichiers

In [100]:
import os
os.getcwd()
#os.mkdir('lapin')
#os.listdir()
#os.chdir('lapin')
os.getcwd()

'/Users/vincentqueffelec/Dropbox/Cours_Info_MP/Notebooks_cours/lapin'

* Windows : \ \ (racine)et \
* Unix : /

#### Retour arrière

In [103]:
#os.chdir('..')
os.chdir('/Users/vincentqueffelec/Dropbox/Cours_Info_MP/Notebooks_cours')
os.getcwd()
#os.chdir('lapin')#chemin relatif

'/Users/vincentqueffelec/Dropbox/Cours_Info_MP/Notebooks_cours'

#### Modes d'ouverture
* 'r' : lecture simple
* 'w' : écriture et écrasement
* 'a' : ajout en fin
* 'rb' : lecture binaire    
$\rightarrow$ $\verb"open"$ $\leftrightarrow$ flot de données

In [104]:
fich=open('fichier.txt','w')#Création
print(fich)

<_io.TextIOWrapper name='fichier.txt' mode='w' encoding='UTF-8'>


$\rightarrow$ Flot de données textuelles

In [105]:
fich.write('une premiere ligne')

18

In [106]:
fich.write('une deuxieme ligne')

18

In [107]:
fich.read()#impossible --> voir fichier

UnsupportedOperation: not readable

In [109]:
fich.close() #MAJ --> voir fichier
fich=open('fichier.txt','r') 

$\rightarrow$  Notion de "commit"

In [111]:
fich.close()
lapin=open('fichier.txt','a')
lapin.write('\n une autre vraie ligne\n ')

25

In [113]:
lapin.close()
lapin=open('fichier.txt','r')
lapin.read()

'une premiere ligneune deuxieme ligne\n une autre vraie ligne\n \n une autre vraie ligne\n '

In [114]:
lapin.close()
lapin=open('fichier.txt','r')
lapin.readline()

'une premiere ligneune deuxieme ligne\n'

In [115]:
lapin.readline()

' une autre vraie ligne\n'

In [119]:
lapin.readline()

''

Il n'y a plus rien ! $\rightarrow$ curseur

In [120]:
lapin.close()
fich=open('fichier.txt','r')
L=fich.readlines()

In [78]:
for elt in L:
    print(elt)

une premiere ligneune deuxieme ligne

 une autre vraie ligne

 


#### Gestion automatique
$\rightarrow$ $\verb"with"$    
$\rightarrow$ context manager    
$\rightarrow$ ouverture et fermeture automatiques

In [121]:
with open('fichier.txt','r') as ancien, open('fichierbis.txt','w') as nouv :
    for ligne in ancien:
        nouv.write(ligne)
fich=open('fichierbis.txt')
fich.read()

'une premiere ligneune deuxieme ligne\n une autre vraie ligne\n \n une autre vraie ligne\n '

# Dictionnaires : Tout a disparu !!